/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BulletinService } from "../bulletin.service";
import { BulletinCreateInput } from "./BulletinCreateInput";
import { Bulletin } from "./Bulletin";
import { BulletinFindManyArgs } from "./BulletinFindManyArgs";
import { BulletinWhereUniqueInput } from "./BulletinWhereUniqueInput";
import { BulletinUpdateInput } from "./BulletinUpdateInput";
import { ImageFindManyArgs } from "../../image/base/ImageFindManyArgs";
import { Image } from "../../image/base/Image";
import { ImageWhereUniqueInput } from "../../image/base/ImageWhereUniqueInput";

export class BulletinControllerBase {
  constructor(protected readonly service: BulletinService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Bulletin })
  async createBulletin(
    @common.Body() data: BulletinCreateInput
  ): Promise<Bulletin> {
    return await this.service.createBulletin({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        title: true,
        author: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Bulletin] })
  @ApiNestedQuery(BulletinFindManyArgs)
  async bulletins(@common.Req() request: Request): Promise<Bulletin[]> {
    const args = plainToClass(BulletinFindManyArgs, request.query);
    return this.service.bulletins({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        title: true,
        author: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Bulletin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async bulletin(
    @common.Param() params: BulletinWhereUniqueInput
  ): Promise<Bulletin | null> {
    const result = await this.service.bulletin({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        title: true,
        author: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Bulletin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateBulletin(
    @common.Param() params: BulletinWhereUniqueInput,
    @common.Body() data: BulletinUpdateInput
  ): Promise<Bulletin | null> {
    try {
      return await this.service.updateBulletin({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          title: true,
          author: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Bulletin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteBulletin(
    @common.Param() params: BulletinWhereUniqueInput
  ): Promise<Bulletin | null> {
    try {
      return await this.service.deleteBulletin({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          description: true,
          title: true,
          author: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/images")
  @ApiNestedQuery(ImageFindManyArgs)
  async findImages(
    @common.Req() request: Request,
    @common.Param() params: BulletinWhereUniqueInput
  ): Promise<Image[]> {
    const query = plainToClass(ImageFindManyArgs, request.query);
    const results = await this.service.findImages(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,

        bulletin: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/images")
  async connectImages(
    @common.Param() params: BulletinWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      images: {
        connect: body,
      },
    };
    await this.service.updateBulletin({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/images")
  async updateImages(
    @common.Param() params: BulletinWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      images: {
        set: body,
      },
    };
    await this.service.updateBulletin({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/images")
  async disconnectImages(
    @common.Param() params: BulletinWhereUniqueInput,
    @common.Body() body: ImageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      images: {
        disconnect: body,
      },
    };
    await this.service.updateBulletin({
      where: params,
      data,
      select: { id: true },
    });
  }
}
